AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Demo s3zip application

  SAM Template for S3 zip file functionality using WebSockets

Resources:
  DemoDevS3ZipWebSocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: DemoDevS3ZipWebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"

  ZipRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref DemoDevS3ZipWebSocket
      RouteKey: onzip
      AuthorizationType: NONE
      OperationName: ZipRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ZipInteg

  ZipInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref DemoDevS3ZipWebSocket
      Description: Zip Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ZipFunction.Arn}/invocations

  ZipRouteIntegrationResponse:
     Type: AWS::ApiGatewayV2::IntegrationResponse
     Properties:
      IntegrationId: !Ref ZipInteg
      ApiId: !Ref DemoDevS3ZipWebSocket
      IntegrationResponseKey: $default

  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - ZipRoute
    Properties:
      ApiId: !Ref DemoDevS3ZipWebSocket

  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: demo
      Description: Demo Deployment
      DeploymentId: !Ref Deployment
      ApiId: !Ref DemoDevS3ZipWebSocket

  ZipFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./onzip/
      Handler: app.handler
      Description: 'S3 Zip Handler'
      MemorySize: 8192
      Timeout: 600
      Runtime: nodejs14.x
      Policies:
        - AmazonS3FullAccess
        - AmazonAPIGatewayInvokeFullAccess

  ZipPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - DemoDevS3ZipWebSocket
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ZipFunction
      Principal: apigateway.amazonaws.com

Outputs:
  ZipFunctionArn:
    Description: "Zip function ARN"
    Value: !GetAtt ZipFunction.Arn

  WebSocketURI:
    Description: "The WSS Protocol URI to connect to"
    Value: !Join [ '', [ 'wss://', !Ref DemoDevS3ZipWebSocket, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref 'Stage'] ]
